version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
    ports:
      - 3000:3000
    command: npm run dev
